### ISSUE TITLE
上周整了个新号 5$ 秒没了，原来是这给我暴露了域名

### ISSUE THREAD

**Issue by Camusama** [lzwme/chatgpt-sites#10]

**Comment by Camusama** [comment]
访问控制是 Vercel 的付费功能。如果把 token 放到 Vercel 的process.env 里，别人反代我的域名就能白嫖token了，猜测已有黑产。

**Comment by renxia** [comment]
设置一下密码、安全码、验证码、真人识别等措施是必要的，否则有很多办法可以白嫖的
这里只是简单的搜集 vercel 部署的站点，黑产的话办法只会更多样

**Comment by CharlesCCC** [comment]
我今天查看Vercel的log,也发现好多从lzw.me引流来的访问, 然后能否展开来说说这一个 `别人反代我的域名就能白嫖token了` ? 我不太理解这个怎么做到的.

**Comment by renxia** [comment]
那里只是个导航的作用，如果有很多无refer来源的请求，那是有可能被代理了的。最简单的只需要请求你的api接口就可以

**Comment by CharlesCCC** [comment]
对,这个我懂, 我意思它说的那种白嫖token的情况不是很理解,我希望尽量避免(然后自己可以设个 limit).

**Comment by Camusama** [comment]
指的是我把token配置在vercel 的environment 变量里，打开网页就不用输入token了 。 而别人反代我域名来做请求就消耗了这个token @CharlesCCC

**Comment by CharlesCCC** [comment]
@Camusama Cam 哦哦, 谢谢解释. 我现在API和Access Code也都设置在 环境变量 里了,现在似乎一切都还好.

**Comment by renxia** [comment]
被盯上是必然的，已经收到要求合作抓取免费站点信息的邮件。各位自建站点的同学应当注意安全防范措施。
实际上对于免费访问的方式来说，在每次的请求中都附带一个基于 API KEY 计算的随机指纹验证，就可以有效防范接口被代理白嫖的情况
