### ISSUE TITLE
请勿收录523以及2757

### ISSUE THREAD

**Issue by lainbo** [lzwme/chatgpt-sites#13]
已经开始出现异常流量和异常的key用量消耗

**Comment by lainbo** [comment]
依旧在收录，现在变成了496和2679
https://gpt.lainbo.com/
https://chat-gpt-next-web-lainbo.vercel.app/
这两个域名请不要收录

**Comment by renxia** [comment]
定时任务已自动更新移除，可将上面的内容移除，避免被有心人收集
