### ISSUE TITLE
我想请问一下这个程序是怎么检索到这么多网站的，我的网站没发出来过也被检索到了

### ISSUE THREAD

**Issue by fangyuan99** [lzwme/chatgpt-sites#17]

**Comment by renxia** [comment]
根据 github 的 API 接口可以获取公开 fork 仓库的 commit 和评论信息。
vercel 部署成功后会默认在 commit 下添加评论，包含所有绑定的域名。
此外 vercel 默认生成的域名规则是公开的，可以直接根据 fork 仓库名和你的账号推理出来并尝试。

若您不希望域名被公开，建议额外做以下几点工作：

1. 在 vercel.json 文件中新增配置 `"silent": true`，避免 vercel 评论泄露信息
2. 移除 vercel 默认生成的域名，使用自定义域名规则
3. 避免被搜索引擎索引。在站点根目录下新增 `robots.txt` 文件，内容为：

```
User-agent: *
Disallow: /
```

**Comment by xiaoxx970** [comment]
GFW工作人员过来一看：妙啊正愁找不到封哪些ChatGPT自建站呢，遂全部封之（我的自定义域名指向Vercel的已经被墙了，今天突然好奇谷歌了一下我自己的域名才发现这个项目，不知道你这个列表里被墙的成分有多少）

**Comment by renxia** [comment]
> GFW工作人员过来一看：妙啊正愁找不到封哪些ChatGPT自建站呢，遂全部封之（我的自定义域名指向Vercel的已经被墙了，今天突然好奇谷歌了一下我自己的域名才发现这个项目，不知道你这个列表里被墙的成分有多少）

有道理，计划后续不再新增自定义的个人域名。

**Comment by 6713fgedywrytsaf** [comment]
我是一小白，能加入你们 吗？看着你们的对话挺长见识的。

**Comment by dianso** [comment]
又一个被你们害的墙了
