### ISSUE TITLE
Submit https://chatgpt.peterdavehello.org/

### ISSUE THREAD

**Issue by PeterDaveHello** [lzwme/chatgpt-sites#23]
Free hosting for testing purpose, very fast, and no login/apikey/password/payment needed.

**Comment by PeterDaveHello** [comment]
@renxia I'm planning to shut down this testing purpose site, would you please help remove it? Thanks!

**Comment by renxia** [comment]
ok

**Comment by PeterDaveHello** [comment]
Thanks!
