### ISSUE TITLE
来，加一个

### ISSUE THREAD

**Issue by margox** [lzwme/chatgpt-sites#33]
https://sofast.ai/chat
是将ChatGPT分成了不同的角色方便对话（模型是gpt-3.5-turbo），不是使用开源项目一键部署的那种，近期在快速迭代中。
不需要自己的key，也不需要梯子，目前可以免费体验，但是体验次数不多，然而可以邀请他人参与体验来获得更多体验次数。

**Comment by margox** [comment]
..域名被墙了，凸(艹皿艹 )

**Comment by renxia** [comment]
确实，感觉最近封域名比较严，指向在外网的域名很容易被屏蔽。看上去是SNI阻断的方式。尽量不要用主域名，可以用三级或四级域名尝试
