### ISSUE TITLE
新增免费网站 http://n1.xjai.cc

### ISSUE THREAD

**Issue by webpon** [lzwme/chatgpt-sites#34]
{
  "http://n1.nbai.live": {
      "needKey": -1,             // 是否需要自己输入 API KEY
      "needPwd": -1,             // 是否需要密码、账号登录才能访问
      "needLogin": -1,           // 需要注册或绑定账号登录才可使用
      "needPay": -1,             // 付费应用
      "needVerify": -1,          // 需人工验证确认状态。-1 表示可用且无需程序验证
      "needVPN": -1,             // 需科学上网
      "desc": "描述",
      "title": "免费小杰Ai，基于chatgpt开发"
  },
}

**Comment by renxia** [comment]
好像打不开？
