### ISSUE TITLE
站长你好，TreeMind树图申请入驻贵站，请问有什么要求吗？可以添加一个联系方式吗？

### ISSUE THREAD

**Issue by Wyannnn** [lzwme/chatgpt-sites#44]
站长你好，TreeMind树图申请入驻贵站，请问有什么要求吗？可以添加一个联系方式吗？

**Comment by renxia** [comment]
您好，在这里提交地址、标题、描述等基本信息即可

**Comment by Wyannnn** [comment]
您好，TreeMind树图申请入驻贵站
本站名称：TreeMind树图
 本站链接：https://shutu.cn/?from=sites
 本站描述：新一代“AI人工智能”思维导图
 本站logo：https://bzr12mkgic.feishu.cn/docx/R9XAdFxKyoHLGFxoIZWcjGzjnyg
申请入驻贵站

**Comment by Wyannnn** [comment]
您好，TreeMind树图申请入驻贵站


本站名称：TreeMind树图
&nbsp;本站链接：https://shutu.cn/?from=sites
&nbsp;本站描述：新一代“AI人工智能”思维导图
&nbsp;本站logo：https://bzr12mkgic.feishu.cn/docx/R9XAdFxKyoHLGFxoIZWcjGzjnyg
申请入驻贵站





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lzwme/chatgpt-sites"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月11日(星期四) 凌晨0:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lzwme/chatgpt-sites] 站长你好，TreeMind树图申请入驻贵站，请问有什么要求吗？可以添加一个联系方式吗？ (Issue #44)





 
您好，在这里提交地址、标题、描述等基本信息即可

**Comment by Wyannnn** [comment]
您好，TreeMind树图申请入驻贵站




本站名称：TreeMind树图 本站链接：https://shutu.cn/?from=sites 本站描述：新一代“AI人工智能”思维导图 本站logo：https://bzr12mkgic.feishu.cn/docx/R9XAdFxKyoHLGFxoIZWcjGzjnyg 申请入驻贵站






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lzwme/chatgpt-sites"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月11日(星期四) 凌晨0:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lzwme/chatgpt-sites] 站长你好，TreeMind树图申请入驻贵站，请问有什么要求吗？可以添加一个联系方式吗？ (Issue #44)





 
您好，在这里提交地址、标题、描述等基本信息即可
