### ISSUE TITLE
新增站点https://zyq-chatgpt.github.io/

### ISSUE THREAD

**Issue by zyq-chatgpt** [lzwme/chatgpt-sites#75]
{
"https://zyq-chatgpt.github.io": {
"star": 2,
”source“:"recommend",
"desc": "无需登录，免费使用",
"title": "浪浪山AI-国内永久免费的Chatgpt 镜像，无需登录"
}
}

**Comment by hapi666** [comment]
@zyq-chatgpt 已经不能访问了
